import Link from "next/link";
import { PipelineDiagram } from "@/components/PipelineDiagram";
import { NetworkPreview } from "@/components/NetworkPreview";
import { StudioNextStatus } from "@/components/StudioNextStatus";

const WHY = [
  { icon: "✓", title: "DETERMINISTIC FIRST", body: "Files, functions, strings, and test outcomes are checked with deterministic logic." },
  { icon: "◎", title: "GENLAYER JUDGMENT", body: "Subjective requirements are evaluated through GenLayer’s decentralized AI consensus." },
  { icon: "↔", title: "CONSENSUS", body: "Validators compare stable PASS/FAIL decisions while reasoning can differ." },
  { icon: "▣", title: "AUDITABLE PROOF", body: "The final decision and supporting evidence can be independently verified." },
];

export default function HomePage() {
  return <>
    <section className="grid-bg relative overflow-hidden"><div className="radial-fade absolute inset-0" /><div className="relative mx-auto max-w-6xl px-5 pb-12 pt-12 md:pb-14 md:pt-16"><div className="mx-auto max-w-4xl text-center"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#f4b39b] bg-[#fff0ea] px-4 py-1.5 font-mono text-[11px] font-bold tracking-wide text-[#df4f1f]"><span className="pulse-glow h-1.5 w-1.5 rounded-full bg-[#ff6b35]" />GENLAYER INTELLIGENT CONTRACT · AGENT TANK 2026</div><h1 className="text-5xl font-bold leading-[1.04] tracking-[-.055em] text-[#202124] md:text-7xl">AI agents do the work.<br /><span className="text-[#ff6b35]">AgentzProof proves it.</span></h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-relaxed text-[#6f6b64]">Independent verification of AI-agent work using deterministic checks and GenLayer consensus.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/create" className="btn-primary w-full sm:w-auto">Create Verification <span aria-hidden>→</span></Link><Link href="/jobs" className="btn-secondary w-full sm:w-auto">Explore Verifications <span aria-hidden>↗</span></Link></div></div><div className="mx-auto mt-10 max-w-md"><PipelineDiagram /></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-12 md:py-16"><div className="flex flex-col gap-3 border-b border-[var(--border)] pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Live verification network</p><h2 className="mt-2 text-2xl font-bold tracking-tight md:text-3xl">Browse the work. Inspect the proof.</h2></div><Link href="/jobs" className="text-sm font-bold text-[var(--orange-dark)] hover:underline">View all verifications →</Link></div><div className="network-snapshot mt-5"><div className="network-snapshot-card"><span className="network-dot" /><div><strong>Verification network</strong><span>Evidence-backed work, independently checked</span></div></div><div className="network-metric"><strong>Bradbury</strong><span>Chain 4221</span></div><div className="network-metric"><strong>LIVE</strong><span>on-chain ready</span></div><StudioNextStatus /></div><div className="mt-5"><NetworkPreview /></div></section>
    <section className="border-y border-[#e8e4dc] bg-white"><div className="mx-auto max-w-6xl px-5 py-14 md:py-16"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Why AgentzProof</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Proof for work that matters.</h2><p className="mt-4 text-[var(--muted)]">Traditional smart contracts can verify deterministic facts. They cannot reliably answer: <span className="font-semibold text-[var(--text)]">“Did this AI agent actually complete the work according to the agreement?”</span></p><p className="mt-3 text-[var(--muted)]">AgentzProof combines deterministic evidence checks with GenLayer’s Intelligent Contracts to answer that question.</p></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{WHY.map((item) => <div key={item.title} className="card card-hover p-5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#fff0ea] font-bold text-[#df4f1f]">{item.icon}</span><h3 className="mt-4 text-sm font-bold tracking-wide">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-[var(--muted)]">{item.body}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-14 md:py-16"><div className="grid items-center gap-8 md:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Demo · simulated</p><h2 className="mt-3 text-3xl font-bold tracking-tight">See AgentzProof catch a subtle bug.</h2><p className="mt-4 leading-relaxed text-[var(--muted)]">Watch a password-reset implementation move through evidence review, deterministic checks, and GenLayer consensus. The buggy version fails for a precise reason; the corrected version passes.</p><Link href="/demo" className="btn-primary mt-6">Watch Live Demo <span aria-hidden>→</span></Link></div><div className="card p-5"><div className="mb-3 flex items-center justify-between"><span className="font-mono text-xs text-[var(--muted)]">password-reset · proof preview</span><span className="status-badge status-danger">DEMO · FAILED</span></div>{["Password reset flow", "Token generation", "Password update", "Test coverage", "Expired tokens rejected"].map((label, i) => <div key={label} className="flex items-center justify-between border-t border-[var(--border)] py-3 text-sm"><span className={i === 4 ? "font-semibold" : "text-[var(--muted)]"}>{label}</span><span className={i === 4 ? "decision-fail" : "decision-pass"}>{i === 4 ? "× FAIL" : "✓ PASS"}</span></div>)}</div></div></section>
    <section className="px-5 pb-16"><div className="mx-auto max-w-5xl rounded-2xl bg-[#202124] px-6 py-10 text-center text-white md:px-12"><p className="eyebrow text-[#ff9b78]">Ready to verify?</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Give every agent deliverable a fair, independent check.</h2><p className="mx-auto mt-4 max-w-xl text-[#c8c2b9]">Create an agreement in minutes, then let AgentzProof turn the result into auditable proof.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/create" className="btn-primary">Create Verification <span aria-hidden>→</span></Link><Link href="/about" className="inline-flex min-h-[44px] items-center justify-center rounded-[10px] border border-[#5a554e] px-5 font-bold text-white hover:bg-white/10">How it Works</Link></div></div></section>
  </>;
}
